services:
  feedback-backend:
    image: ghcr.io/sim-assurances/feedback-backend:v2
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://postgres:RepensTO@feedbackmysim-feedbacksbdd-u1x6il:5432/feedback
      JWT_SECRET: d72be9b31a835ef7549d35946754bcdd84eee8bd7155f33880c137bc9368367e9b6ad8b2e251d76448e3fedb40e5450b263cd28c4f9216eeb3625411cf646da2
      JWT_EXPIRES_IN: 24h
      CORS_ORIGIN: https://feedback.mysimassurances.com
      ADMIN_EMAIL: admin@feedback.mysimassurances.com
      ADMIN_PASSWORD: Admin123
    networks:
      - dokploy-network
    restart: unless-stopped

  feedback-frontend:
    image: ghcr.io/sim-assurances/feedback-frontend:v3
    depends_on:
      - feedback-backend
    networks:
      - dokploy-network
    restart: unless-stopped

networks:
  dokploy-network:
    external: true
